FROM rust
RUN rustup component add rust-analysis && \
    rustup component add rust-src && \
    rustup component add rls

ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && usermod --shell /bin/bash $USERNAME

USER $USERNAME